### ISSUE TITLE
[BUG] >PRECISE TITLE<

### ISSUE THREAD

**Issue by bennimedia** [Roo7K1d/RP-Police-Database#2]
I have installed your Script. when i login have this:
Warning: session_start(): Cannot start session when headers already sent/index.php on line 22

Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/w012aff3/b3nni/bm-webseite-2020/mdt-foxcity/index.php:1) in /index.php on line 132

**Comment by Roo7K1d** [comment]
That is not an issue caused by this repo. It has something to do with the other website in your www-folder as `/www/htdocs/w012aff3/b3nni/bm-webseite-2020/mdt-foxcity/index.php` states.
I can not help you with that.
